# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutomer_name', models.CharField(blank=True, max_length=120, null=True)),
                ('customer_feedback', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
