# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecustomer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='customer_feedback',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
