# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.IntegerField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('room_type', models.CharField(blank=True, max_length=120, null=True)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=220, null=True)),
                ('Email', models.CharField(blank=True, max_length=320, null=True)),
                ('Message', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
