# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checkout',
        ),
        migrations.AddField(
            model_name='booking',
            name='datepicker1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='datepicker2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
