# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20180426_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.EmailField(blank=True, max_length=320, null=True),
        ),
    ]
