# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=120, null=True)),
                ('room_cost', models.IntegerField()),
                ('room_description', models.TextField(blank=True, max_length=300, null=True)),
                ('height_field', models.IntegerField(blank=True, null=True)),
                ('width_field', models.IntegerField(blank=True, null=True)),
                ('room_img1', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('room_img2', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('room_img3', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('room_img4', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('room_img5', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('room_facilities', models.TextField(help_text='seperate each item by comma')),
            ],
        ),
    ]
