# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsactivities', '0002_auto_20180423_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='height_field1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_thumImg',
            field=models.ImageField(blank=True, height_field='height_field1', null=True, upload_to='', width_field='width_field1'),
        ),
        migrations.AddField(
            model_name='room',
            name='width_field1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
