# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsactivities', '0003_auto_20180424_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_availability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
