# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsactivities', '0004_auto_20180424_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_accomadete',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
