# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsactivities', '0005_room_room_accomadete'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=120, null=True)),
                ('room_accomadete', models.IntegerField(blank=True, null=True)),
                ('datepicker1', models.DateField(null=True)),
            ],
        ),
    ]
