# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomsactivities', '0006_roomcheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcheck',
            name='datepicker1',
        ),
    ]
